### ISSUE TITLE
 handwired/tractyl_manuform/5x6_right no exists

### ISSUE THREAD

**Issue by jose-sampedro** [Schievel1/dactyl_manuform_r_track#1]
When i run 
git clone https://github.com/Schievel1/qmk_firmware_dm_r_track.git
cd qmk_firmware_dm_r_track/
git checkout tractyl_manuform_enhance
make git-submodule

Directory does not exist
keyboards/handwired/tractyl_manuform/5x6_right/keymaps/yourkeymap/config.h

Thx!

**Comment by Schievel1** [comment]
I hope I understand this correctly.

The "yourkeymap" in the path is just a wildcard for the directory for the keymap you created for yourself.

**Comment by jose-sampedro** [comment]
Perfect!

It was my mistake for not reading correctly.

I finally completed my dactyl manuform trackball thanks to you!

Thank you for your work!!

**Comment by Schievel1** [comment]
Glad to hear that. If you have trouble with the firmware, especially the trackball modes I added, let me know. (In a new issue) I am happy to help and to fix some bugs before I make a PR to QMK.
